import './globals.css'
import { type ReactNode } from 'react'
import { Inter } from 'next/font/google'

import OnchainProviders from './providers'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Swapper',
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <OnchainProviders>{props.children}</OnchainProviders>
      </body>
    </html>
  )
}
